apiVersion: v1
kind: Secret
metadata:
  name: volunteer-secrets
  namespace: volunteer
  labels:
    app.kubernetes.io/name: volunteer-service
    app.kubernetes.io/part-of: solidarytech
type: Opaque
Data:
  AWS_REGION: dXMtZWFzdC0x
  AWS_DYNAMODB_TABLE: U29saWRhcnlUZWNoVm9sdW50ZWVycw==
