apiVersion: v1
kind: ServiceAccount
metadata:
  name: volunteer-service
  namespace: volunteer
  labels:
    app.kubernetes.io/name: volunteer-service
    app.kubernetes.io/part-of: solidarytech
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::solidarytech-eks:role/solidarytech-volunteer-service