apiVersion: v1
kind: Service
metadata:
  name: donation-service
  namespace: donation
  labels:
    app: donation-service
    app.kubernetes.io/name: donation-service
    app.kubernetes.io/part-of: solidarytech
spec:
  selector:
    app: donation-service
  ports:
    - name: http
      port: 80
      targetPort: http
