apiVersion: v1
kind: ServiceAccount
metadata:
  name: ngo-service
  namespace: ngo
  labels:
    app.kubernetes.io/name: ngo-service
    app.kubernetes.io/part-of: solidarytech
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::solidarytech-eks:role/solidarytech-ngo-service
