apiVersion: v1
kind: Namespace
metadata:
  name: ngo
  labels:
    app.kubernetes.io/part-of: solidarytech
    cost-center: NGO-Core
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: donation
  labels:
    app.kubernetes.io/part-of: solidarytech
    cost-center: NGO-Core
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: volunteer
  labels:
    app.kubernetes.io/part-of: solidarytech
    cost-center: NGO-Core
    environment: production
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: observability
#   labels:
#     app.kubernetes.io/part-of: solidarytech
#     cost-center: NGO-Core
#     environment: production
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: disaster-recovery
#   labels:
#     app.kubernetes.io/part-of: solidarytech
#     cost-center: NGO-Core
#     environment: production
