apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 86.0.1
    helm:
      values: |
        fullnameOverride: kube-prometheus-stack
        commonLabels:
          app.kubernetes.io/part-of: solidarytech
          cost-center: NGO-Core

        grafana:
          adminPassword: solidarytech-admin
          defaultDashboardsTimezone: America/Sao_Paulo
          sidecar:
            dashboards:
              enabled: true
              searchNamespace: ALL
              label: grafana_dashboard
              labelValue: "1"
            datasources:
              enabled: true
          additionalDataSources:
            - name: Loki
              uid: loki
              type: loki
              access: proxy
              url: http://loki-gateway.observability.svc.cluster.local
              isDefault: false
              editable: true

        prometheus:
          prometheusSpec:
            retention: 15d
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            resources:
              requests:
                cpu: 300m
                memory: 1Gi
              limits:
                cpu: "1"
                memory: 2Gi

        alertmanager:
          alertmanagerSpec:
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi

        prometheus-node-exporter:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 150m
              memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
