apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SEU_USUARIO/hackathon-DCLT.git
    targetRevision: main
    path: GitOps/observability
    directory:
      recurse: true
      exclude: "{apps/**,newrelic-secret.example.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
